[project]
name = "resume-critquer"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.39.0",
    "markdown-it-py[plugins]>=3.0.0",
    "python-dotenv>=1.1.1",
    "sseclient-py>=1.8.0",
    "streamlit>=1.46.1",
    "weasyprint>=65.1",
]
